### ISSUE TITLE
[Test] 웹서버로 Api 라우팅하기 - 유저 정보 조회 #2 의 테스트 코드 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#15]
## Desc
- #2 의 테스트 코드

## Detail
Controller 테스트 코드 Get 위주 

## Todo
- [x] GET /users/{nickname}/detail
- [x] GET /users/{nickname}/achievements?selected={true}
- [x] GET /users/{nickname}/emojis?selected={true}
- [x] GET /users/{nickname}/titles
- [x] GET /users/{nickname}/stats/total
- [x] GET /users/{nickname}/stats/season
- [x] GET /users/{nickname}/ranks/total
- [x] GET /users/{nickname}/ranks/season
