### ISSUE TITLE
[Feat] 커스텀 데코레이터 만들기 ValidatePipe

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#24]
## Desc

- 커스텀 데코레이터 만들기
## Detail

- 배열안의 인자들 하나하나 숫자와 null이 가능한것.
- 배열의 사이즈 고정하는것.
## Todo
- [x] 깃 리버트 해서 꼬인거 풀기
- [x] 배열안의 인자들 하나하나 숫자와 null이 가능한것.
- [x] 배열의 사이즈 고정하는것. achievement는 3이고 emoji는 4 -> .env로 관리
- [x]  적용되는지 검증하기
