### ISSUE TITLE
[Feat / Chat] 채팅 서버 라우팅 하기 - 친구 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#34]
## Desc

채팅 서버 라우팅하기 - 친구 
## Detail

친구 기능에 대한 API 라우팅 하기 
## Todo
- [x] GET /users/friends
- [x] POST /users/friend/pendings/:nickname
- [x] GET /users/friends/pendings
- [x] POST /users/friends/:nickname
- [x] DELETE /users/friends/pendings/:nickname
- [x] DELETE /users/friends/:nickname
