### ISSUE TITLE
[Feat / Chat] 채팅 서버 라우팅 하기 - 채팅 admin

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#36]
## Desc

- 테스트 코드 짜기
- 채팅 서버 라우팅 하기 - 채팅 admin

## Todo
@Controller('/channels')
- [x]   @Patch('/:roomId')
- [x]   @Delete('/:roomId')
- [x]   @Post('/:roomId/admin/:nickname')
- [x]   @Delete('/:roomId/admin/:nickname')
- [x]   @Post('/:roomId/ban/:nickname')
- [x]   @Delete('/:roomId/kick/:nickname')
- [x]   @Post('/:roomId/mute/:nickname')
- [x]   @Delete('/:roomId/mute/:nickname')

## Etc

채팅 라우팅 끝나고 dtos 폴더 안에 channels, friends 따로 만들기 아님 각각 이 가지고 있기 정하기 -> 이슈 파서 풀리퀘 따로 날리기
