### ISSUE TITLE
[Feat / Chat] 채팅 서버 라우팅 하기 - 채팅 normal 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#44]
## Desc

 채팅 서버 라우팅 하기 - 채팅 normal 

## Todo
@Controller('/channels')
- [x]   @Get('/')
- [x]   @Get('/:roomId/participants')
- [x]   @Post('/')
- [x]   @Post('/:roomId/participants')
- [x]   @Delete('/:roomId/participants')
- [x]   @Post('/:roomId/invitation/:nickname')
- [x]   @Post('/:roomId/magicpass')
- [x]   @Post('/:roomId/chats')
- [x]   @Get('/me')
- [x]   @Get('/:roomId/chats')
