### ISSUE TITLE
[Fix] 합친다 프로토콜시 발생한 에러 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#48]
## Desc
합친다 프로토콜시 발생한 에러

## Todo
- [x] 토큰 등록하는 부분에 roleType추가 
```
  async createJwtFromUser(user: AuthDto): Promise<string> {
    const token = this.jwtService.sign({
      id: user.id,
      nickname: user.nickname,
      secondAuthRequired: user.secondAuthRequired,
      roleType: user.roleType,
    });
    return token;
  }
  ```

- [x] 디폴트로 null설정해주기
```
  @Column({ name: 'nickname', default: null })
  nickname: string;
  ```

- [x] 키값 Token -> accessToken 으로 수정 
```
export class JwtDto {
  accessToken: string;
}
```
```
  @Post('/42')
  async fortyTwoLogin(@Body('authCode') code: string): Promise<JwtDto> {
    this.logger.log(code);
    const accessToken: string = await this.authService.getFTAccessToken(code);
    const userInfo: AuthDto = await this.authService.getFTUserInfo(accessToken);
    const jwt: string = await this.authService.createJwtFromUser(userInfo);
    this.logger.log(jwt);
    return { accessToken: jwt };
  }

```
- [x] getUserMeDetail Controller 구현 
```
  @Get('/me')
  async getUserMeDetail(@Req() request) {
    const btoken: string = request.headers.authorization;
    console.log(btoken)
    const token = btoken?.split(' ')[1];
    console.log(token);
    return await this.authService.getUserMe({ token });
  }
  ```

- [x] noname 이여서 signup으로 와서 닉네임 설정했을시 accessToken 을 roleType Member로 새로 토큰 업데이트해서 주는로직
```
 @Post('/signup')
  async signUp(@Body() body: SignUpRequestDto, @Req() req): Promise<JwtDto> {
    const token: string = req.headers.authorization?.split(' ')[1];      // 기존 에 가지고 있던 noname 토큰
    const user: TokenInterface = await this.jwtService.verify(token); //일단 그 토큰 우리가 발급했는지 확인하고
    const userId: number = user.id;
    const signedUser: AuthDto = await this.authService.signUp({
      userId,
      nickname: body.nickname,
      imageId: body.imgId,
    });        // signUp 함수 안에서 roleTyep 설정한 객체를 반환 받아서 
    const accessToken = await this.authService.createJwtFromUser(signedUser); //  타입이 업데이트된 토큰을 다시 발생하고

    return { accessToken: accessToken }; // 리턴해준다
  }
  ```
  
```
async signUp(signUpDto: SignUpDto): Promise<AuthDto> {
    const { user, profileImage } = await this.validateSignUp(signUpDto);
    return await this.userRepository.signUp({
      user,
      profileImage,
      nickname: signUpDto.nickname,
    });
  }
  ```
  
  ```
   async signUp(updateDto: UpdateUserSignUpDto): Promise<AuthDto> {
    updateDto.user.image = updateDto.profileImage;
    updateDto.user.nickname = updateDto.nickname;
    const user: User = await this.repository.save(updateDto.user);

    return {
      id: user.id,
      nickname: user.nickname,
      secondAuthRequired: false,
      roleType: ROLETYPE_MEMBER,
    };
  }
  ```
