### ISSUE TITLE
[Fix] Test code 전면수정 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#58]
## Desc

- Appmodule에 testmodule  빼기
- #45
- 전반적으로 chatServer 테스트 코드 형식에 맞게 수정하자 
- DB 도 각 DB name에 넣고 테스트 하자

## Todo
- [ ] Appmodule에 testmodule  빼기
- [ ] #45
- [ ] 전반적으로 chatServer 테스트 코드 형식에 맞게 수정하자 
- [ ] DB 도 각 DB name에 넣고 테스트 하자
