### ISSUE TITLE
[Feat /  Chat] Notification 라우팅 하기 

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#66]
## Desc

Notification 라우팅 하기 
## Todo
- [x] GET /users/notifications/friends
- [x]  GET /users/notifications/channels
- [x]  DELETE /users/notifications/channels/{id}
