### ISSUE TITLE
[Feat /  Game] Game 라우팅 하기  

### ISSUE THREAD

**Issue by maindishes** [Dr-Pong/dr_pong_api_gateway#80]
## Desc

- Game 서버 api 라우팅 하기 
- 라우팅 테스트코드 작성하기

## Todo
- [x] @Post('/invitation/:nickname')
- [x] @Delete('/invitation')
- [x] @Patch('/invitation/:id')
- [x] @Delete('/invitation/:id')
- [x] @Post('/queue/:type/:mode')
- [x] @Delete('/queue')
